name: Terraform CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1

      # Step 4: Terraform Init (only if no previous state)
      - name: Check Terraform Init
        id: init_check
        run: |
          if [ ! -d .terraform ]; then
            echo "need to initialize terraform"
            echo "::set-output name=needs_init::true"
          else
            echo "::set-output name=needs_init::false"
          fi

      # Step 5: Terraform Init (conditionally)
      - name: Terraform Init
        if: steps.init_check.outputs.needs_init == 'true'
        run: terraform init

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
